### ISSUE TITLE
Publish on F-droid

### ISSUE THREAD

**Issue by mdecorde** [ianhanniballake/ContractionTimer#132]
Why not publish your app on f-droid ? https://f-droid.org

There are around 100+ contraction timer apps on Google Play but 0 on f-droid and yours is open-source ! \o/

see https://f-droid.org/forums/forum/submission-queue and https://f-droid.org/wiki/page/Inclusion_Policy

**Comment by guysoft** [comment]
Same issue here too. Would you like help to do this?

**Comment by ianhanniballake** [comment]
The only valid place to download Contraction Timer is via Google Play. That will always remain the case, sorry.
